production:
  secret_token: # 'rake secret' to make a new token
  site_name: Campo
  host:
  google_custom_search_id: 
  admin_emails:
    - admin@your_email.com
    - admin2@your_email.com
  # gmail smtp
  smtp_username:
  smtp_password:

development:
  secret_token: '4c8418b11e5529b65f7fff02e2e496f0cbdbac990b8453cfe3c67e747469984945bc10039e542c76cb0f8226a950a2c1d55e816fced1a0d65d27d39bcb4fd427'
  site_name: CodeCampo
  host: 'localhost:3000'
  google_custom_search_id: 
  admin_emails:
    - admin@codecampo.com
  # gmail smtp
  smtp_username:
  smtp_password:

test:
  secret_token: '4c8418b11e5529b65f7fff02e2e496f0cbdbac990b8453cfe3c67e747469984945bc10039e542c76cb0f8226a950a2c1d55e816fced1a0d65d27d39bcb4fd427'
  site_name: CodeCampo
  host: 'localhost:3000'
  google_custom_search_id: 
  admin_emails:
    - admin@codecampo.com
