production:
  site_name: your_site_name
  organize_name: your_organize_name
  organize_url: your_organize_url
  host:
  admin_emails:
    - admin@your_email.com
    - admin2@your_email.com
  # gmail smtp
  smtp_username:
  smtp_password:

# example
defaults: &defaults
  site_name: CodeCampo
  organize_name: CodeCampo
  organize_url: http://codecampo.com
  host: 'localhost:3000'
  admin_emails:
    - admin@codecampo.com

development:
  <<: *defaults
  # gmail smtp
  smtp_username:
  smtp_password:

test:
  <<: *defaults
